/*
Used Oracle https://livesql.oracle.com/
*/

SELECT COUNT(*) AS SCAN_COUNT
FROM COVID19SCAN
WHERE SCAN_DATE
BETWEEN '10-OCT-21' AND '15-OCT-21'
;

SELECT COUNT(*) AS TEST_COUNT
FROM COVID19TEST
WHERE TEST_DATE
BETWEEN '15-OCT-21' AND '17-OCT-21'
;

SELECT COUNT(*) AS SELF_REPROTED_EMP_COUNT
FROM HEALTHSTATUS
WHERE STATUS_DATE 
BETWEEN '15-OCT-21' AND '17-OCT-21'
;

SELECT COUNT(*) AS CASE_COUNT
FROM COVID19CASE
WHERE CASE_DATE 
BETWEEN '15-OCT-21' AND '17-OCT-21'
;
